[build]
  command = "bash -c 'curl -sSL https://install.python-poetry.org | python3.8 && export PATH=\"/opt/buildhome/.local/bin:$PATH\" && poetry install && poetry run uvicorn packages.crm.crm.crm_api:app --host 0.0.0.0 --port 8000'"