[build]
  command = """
    curl -sSL https://install.python-poetry.org | python3 &&
    poetry install &&
    poetry run uvicorn packages.public_api.app:app --host 0.0.0.0 --port 8080
  """
  publish = "public" 